### ISSUE TITLE
Section for pinning services

### ISSUE THREAD

**Issue by agentofuser** [ipfs/awesome-ipfs#236] opened 2019-02-13 02:34 UTC
So far I only know of Pinata.cloud, which is listed under "Apps", but it would be nice to have a list of alternative services where one can pin content to be always available. Description could include if there is a free tier, for instance.

**Comment by koalalorenzo** [comment] 2019-02-13 08:32
Duplicate of https://github.com/ipfs/awesome-ipfs/issues/168
Closing

**Closed by koalalorenzo** 2019-02-13 08:32 UTC
