### ISSUE TITLE
Zoom in on hover makes the project text blurry

### ISSUE THREAD

**Issue by Frijol** [ipfs/awesome-ipfs#241] opened 2019-03-26 19:01 UTC
![Screen Shot 2019-03-26 at 11 58 25 AM](https://user-images.githubusercontent.com/454690/55025659-9e510080-4fbe-11e9-9b0c-f9842ad39b70.png)

Notice that lightly fuzzy text on the Computes project listing vs. the PubSub project listing to its right. Is there a different way to zoom on a highlighted project so the text doesn't go blurry?

**Comment by autonome** [comment] 2019-05-21 20:45
Thanks for reporting @Frijol!

Which browser and OS are you using?

I cannot reproduce the problem on Firefox Nightly or Chrome Canary on Mac. Are you using Windows or Linux?

**Comment by Frijol** [comment] 2019-05-21 21:39
No, Chrome on Mac– specifically https://whatsmybrowser.org/b/XEWTYQK

**Comment by autonome** [comment] 2019-05-23 00:24
Do you have a Retina screen? Maybe this is only non-Retina...

**Comment by Frijol** [comment] 2019-05-23 15:26
uh, not sure. 2014 Air, if that helps you. I'm surprised it's an isolated issue; expected it to be an issue with CSS zoom or something

**Comment by olizilla** [comment] 2019-05-24 09:00
Hi @Frijol 👋 ... that is an odd one, I'm unable to reproduce on Chrome or Firefox stable releases, but that's on a retina screen 2018 mac. Perhaps it appears on non-hidpi screens. Will test on another machine.

**Comment by olizilla** [comment] 2019-05-24 09:08
In general, the zoom on hover is a little suprising, and if it doesn't look good then we should consider disabling it and replacing it with a calmer alternative.

**Comment by victorb** [comment] 2019-05-24 11:53
Seeing the same on Chromium browsers but not on Firefox. Only happens when you hover the elements.

Usually, funky issues with `transform` can be fixed with something like setting `translateZ(0)` to force hardware acceleration or setting `backface-visibility` to `hidden` for simplifying what the render engine needs to do.

**Closed** 2019-07-15 22:13 UTC
